config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :cats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def new
    @cat = Cat.new
  end

  def create
    Cat.create(cat_params)
    redirect_to cats_path
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cats/index.html.erb
<div class="container">
  <header class="header">
  <h1>Feeling that Inspo! Inspirational Cats</h1>
  </header>
</div>
<div class="padded-container">

<h2>Cats: some good boys (and girls):</h2>
<p><%= link_to 'Add yours', new_cat_path %></p>
<hr />
<h3>Cat Number | Cat Name | Cat Description </h3>
<% @cats.each_with_index do |cat, index| %>



<p><%= index + 1 %> | <strong><%= cat.name %></strong> | <%= cat.description %></p>
<% end %>

</div>

app/views/cats/new.html.erb
<div class="container">
  <header class="header">
  <h1>Feeling that Inspo! Inspirational Cats</h1>
  </header>
</div>
<div class="padded-container">

<h1>Enter Your Cat Info</h1>

<%= simple_form_for @cat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit 'Create' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inspo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="container">
  <header class="header">
  <h1>Feeling that Inspo! Inspirational Quotes</h1>
  </header>
</div>
<div class="container">
  <div class="row">
    <blockquote cite="http://quotes.rest/qod.json">Remove the temptation to settle for anything short of what you deserve.
    </blockquote>
    <cite>Lorii Myers</cite>

  </div>
</div>